module.exports = {
  DB_USERNAME: process.env.MONGO_INITDB_ROOT_USERNAME,
  DB_PASSWORD: process.env.MONGO_INITDB_ROOT_PASSWORD,
  DB_IP: process.env.MONGO_INITDB_IP,
  DB_PORT: process.env.MONGO_INITDB_PORT || 27017,
  DB_NAME: process.env.MONGO_INITDB_DATABASE,
};
