version: "3"

services:
  # MongoDB service
  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - mongo-db:/data/db
      - ./server/src/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Node API service
  api:
    container_name: node-api
    build:
      context: ./server
      args:
        - SERVER_PORT=3000
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app:ro
      - /app/node_modules
    depends_on:
      - mongo

volumes:
  mongo-db: {}
