version: "3"

services:
  # Node API service
  api:
    container_name: node-api
    build: ./server
    ports:
      - "3000:${SERVER_PORT}"
    volumes:
      - ./server:/app:ro
      - /app/node_modules
    env_file:
      - ./server/.env
