version: "3"

services:
  # MongoDB service
  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - mongo-db:/data/db
      - ./server/src/db/db.init.js:/docker-entrypoint-initdb.d/db.init.js:ro

  # Node API service
  api:
    container_name: node-api
    build:
      context: ./server
      args:
        - DOCKER_SERVER_PORT=${DOCKER_SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${DOCKER_SERVER_PORT}"
    env_file:
      - .env
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  client:
    container_name: vue-client
    build:
      context: ./client
      args:
        - DOCKER_CLIENT_PORT=${DOCKER_CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${DOCKER_CLIENT_PORT}"
    env_file:
      - .env
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  mongo-db: {}
