version: "3"

services:
  # Node API service
  api:
    container_name: node-api
    env_file:
      - ./server/.env
    build:
      context: ./server
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "3000:${SERVER_PORT}"
    volumes:
      - ./server:/app:ro
      - /app/node_modules
